import { State } from "@/types/interfaces";

const mockedState = {
  currentUser: localStorage.getItem("userData") ? JSON.parse(localStorage.getItem("userData") || "") : {},
  // eslint-disable-next-line no-unneeded-ternary
  isUserAuthenticated: false,
  groups: [],
  userGroups: [],
  currentGroup: {},
  loadedUsersFromGroup: [],
  groupErrors: [],
  allUsers: [],
  isRegistered: false,
  isWrongEmailOnRegister: false,
  isLoading: false,
  userId: "",
  token: "",
  refreshToken: "",
  firstName: "",
  lastName: "",
  user: {
    id: "",
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    adminAccess: false,
    teacherAccess: false,
    studentAccess: false,
    groups: [],
    image: "",
    homeworkToCheck: [],
    teacherGroups: [],
    studentGroups: [],
    info: [],
  },
  lastLoadedUser: {},
  lessons: [],
  groupLessons: [],
  webContent: {
    posts: [
      {
        title: "ОБУЧЕНИЕ В ШКОЛЕ / УРОВНИ text-disabled",
        body: '<h1>&nbsp;</h1><h2 style="-webkit-text-stroke-width:0px;color:rgb(213, 151, 88);font-family:&quot;Noto Sans&quot;, Arial, sans-serif;font-size:3.6rem;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:0.1em;line-height:1.1875;margin:0px 0px 2rem;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:uppercase;white-space:normal;widows:2;word-spacing:0px;"><span style="color:rgb(0,51,102);"><span style="margin-top:0px;"><strong>ОБУЧЕНИЕ В ШКОЛЕ</strong></span></span></h2>',
        category: "Курсы",
        image: "",
        id: "624a945fa4a7260aa1b63087",
      },
      {
        title: "Онлайн ДЛЯ ПРОДОЛЖАЮЩИХ Не редактировать этот заголовок! text-disabled",
        body: '<h1>ПОРТУГАЛЬСКИЙ ДЛЯ ПРОДОЛЖАЮЩИХ ОНЛАЙН</h1><p style="-webkit-text-stroke-width:0px;color:rgb(0, 0, 0);font-family:&quot;Noto Sans&quot;, Arial, sans-serif;font-size:17px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;"><a style="background-color:transparent;color:rgb(213, 151, 88);margin-top:0px;text-decoration:none;transition:color 0.2s ease 0s;" target="_blank" rel="noopener noreferrer" href="https://forms.gle/TqUaHodSEQTKiHYD9">ПРОВЕРИТЬ СВОЙ УРОВЕНЬ ПОРТУГАЛЬСКОГО</a></p>',
        category: "Курсы",
        image: "",
        id: "624a945fa4a7260aa1b63088",
      },
      {
        title: "Атмосфера - полное описание text-disabled",
        body: '<h1>&nbsp;</h1><p>В большинстве отзывов наши студенты говорят об особенной, домашней обстановке в школе, о дружелюбной атмосфере тепла и уюта.&nbsp;Пожалуй, дело&nbsp;в том, что мы сами относимся к Via Roma как к дому.<br>И, конечно, самое важное — это какие в этом доме люди и отношения, которые между ними складываются.&nbsp;</p><p>Но есть и более «осязаемые» элементы нашей атмосферы:</p><p>1. Во-первых, у школы <strong>удобное помещение в 5 минутах от Василеостровской</strong>, в центре города и рядом с метро. В нашей мансарде светлые аудитории с большими окнами, здесь приятно учиться.</p><p>&nbsp;<img src="https://s26.postimg.cc/j6figpl9l/Be_Funky_Collageatm_500x366.jpg" alt=""></p><p>2. В школе есть<strong> библиотека</strong> книг на итальянском и русском о языке и культуре Италии. Студенты берут их домой почитать. Тем, кто хочет учиться&nbsp;и узнавать&nbsp;больше, мы с удовольствием рекомендуем литературу и фильмы.</p><p>',
        category: "Атмосфера",
        image: "",
        id: "624a945fa4a7260aa1b6309a",
      },
      {
        title: "New Year Fest",
        body: "<h1>&nbsp;</h1><p>Quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architectoa..</p>",
        category: "Мероприятия",
        image: "",
        id: "624a945fa4a7260aa1b63094",
      },
      {
        title: "Набор в онлайн группу А1",
        body: '<h1>&nbsp;</h1><p><span style="color:rgb(0,0,0);"><span style="-webkit-text-stroke-width:0px;display:inline !important;float:none;font-family:&quot;Noto Sans&quot;, Arial, sans-serif;font-size:17px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Напоминаем, что идёт набор в онлайн группы для начинающих А1, расписание и подробности тут. &nbsp;</span></span></p>',
        category: "Новости",
        id: "624a945fa4a7260aa1b63089",
      },
      {
        title: "Атмосфера - главная страница text-disabled",
        body: "<h1>&nbsp;</h1><p>Школа небольшая и уютная. Аудитории школы находятся в мансарде. В перерывах пьём чай (иногда вино), едим печенье и листаем книги на итальянском.</p>",
        category: "Атмосфера",
        id: "624a945fa4a7260aa1b63095",
      },
      {
        title: "Лексический подход - главная страница text-disabled",
        body: "<h1>&nbsp;</h1><p>Преподаём по лексическому подходу — то есть делаем акцент на запоминании и использовании не отдельных слов, а фраз и словосочетаний — так легче запоминать слова и легче научиться разговаривать.</p>",
        category: "Методика",
        id: "624a945fa4a7260aa1b63096",
      },
      {
        title: "CHEGUEI A APRENDER TUDO!",
        body: '<h1>&nbsp;</h1><p><span style="background-color:rgb(255,255,255);color:rgb(0,0,0);"><span>я в конце концов все выучила!</span></span><br><br><span style="background-color:rgb(255,255,255);color:rgb(0,0,0);"><span>Давайте сегодня вспомним интересную конструкцию chegar a + infinitivo. Она означает, что человек старался-старался, и вот в итоге что-то получилось (или нет). Например:</span></span><br><br><span style="background-color:rgb(255,255,255);color:rgb(0,0,0);"><span>Não cheguei a falar com ele. - Мне не удалось с ним поговорить.</span></span><br><br><span style="background-color:rgb(255,255,255);color:rgb(0,0,0);"><span>Chegámos a comprar os bilhetes a Portugal. - Мы таки купили билеты в Португалию.</span></span><br><br><span style="background-color:rgb(255,255,255);color:rgb(0,0,0);"><span>Cheguei a perder 5 kg! - Мне удалось похудеть на 5 кг!</span></span></figure>',
        category: "Материалы",
        image: "https://storage.googleapis.com/bairro-alto.appspot.com/chegar-1645545472612.jpg",
        id: "624a945fa4a7260aa1b630a1",
      },
      {
        title: "Артикли в португальском",
        body: '<h1>&nbsp;</h1><figure class="image image_resized" style="width:98.52%;"><img srcset="https://storage.googleapis.com/bairro-alto.appspot.com/articles-1645544618030.jpg 360w" sizes="100vw" width="360"></figure><p><span style="background-color:rgb(255,255,255);color:rgb(0,0,0);"><span>Друзья, приглашаем на второй поток мини-спецкурса </span></span><a target="_blank" rel="noopener noreferrer" href="https://vk.com/id95743">Маргариты Козарович</a><span style="background-color:rgb(255,255,255);color:rgb(0,0,0);"><span> по АРТИКЛЯМ в португальском языке!</span></span><br><br><span style="background-color:rgb(255,255,255);color:rgb(0,0,0);"><span>Мы обратили внимание на то, что ученики делают много однотипных ошибок, связанных с артиклем, и, что удивительно, их делают даже те, кто хорошо говорит на других романских языках. </p>',
        category: "Спецкурсы",
        image: "https://storage.googleapis.com/bairro-alto.appspot.com/articles-1645544618030.jpg",
        id: "624a945fa4a7260aa1b630b0",
      },
      {
        title: "Онлайн ДЛЯ НАЧИНАЮЩИХ text-disabled",
        body: '<h1>Португальский ДЛЯ НАЧИНАЮЩИХ ОНЛАЙН</h1><p style="-webkit-text-stroke-width:0px;color:rgb(0, 0, 0);font-family:&quot;Noto Sans&quot;, Arial, sans-serif;font-size:17px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">',
        category: "Курсы",
        id: "624a945fa4a7260aa1b630b3",
      },
      {
        title: "Офлайн ДЛЯ ПРОДОЛЖАЮЩИХ text-disabled",
        body: '<h1>ПОРТУГАЛЬСКИЙ ДЛЯ ПРОДОЛЖАЮЩИХ ОФЛАЙН</h1><p style="-webkit-text-stroke-width:0px;color:rgb(0, 0, 0);font-family:&quot;Noto Sans&quot;, Arial, sans-serif;font-size:17px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1rem;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">',
        category: "Курсы",
        id: "624a945fa4a7260aa1b630b5",
      },
    ],
    categories: [
      { title: "Мероприятия", slug: "Мероприятия", id: "624a945fa4a7260aa1b630b6" },
      { title: "Спецкурсы", slug: "Спецкурсы", id: "624a945fa4a7260aa1b630b7" },
      { title: "Курсы", slug: "Курсы", id: "624a945fa4a7260aa1b630b8" },
      { title: "Материалы", slug: "Материалы", id: "624a945fa4a7260aa1b630b9" },
      { title: "Преподаватели", slug: "Преподаватели", id: "624a945fa4a7260aa1b630ba" },
      { title: "Отзывы", slug: "Отзывы", id: "624a945fa4a7260aa1b630bb" },
      { title: "Атмосфера", slug: "Атмосфера", id: "624a945fa4a7260aa1b630bc" },
      { title: "Новости", slug: "Новости", id: "624a945fa4a7260aa1b630bd" },
      { title: "Методика", slug: "Методика", id: "624a945fa4a7260aa1b630be" },
      { title: "Группы", slug: "Группы", id: "624a945fa4a7260aa1b630bf" },
    ],
  },
  courseNames: {
    courseNames: ["name"],
  },
};
export default mockedState as unknown as State;
